import jsPDF from 'jspdf';

interface ExportOptions {
    title?: string;
    clientTag?: string;
    generatorType?: 'RBT Session Notes' | 'BCBA Weekly Report' | 'Session Note';
    notes: string;
}

/**
 * Exports clinical notes text into a professional PDF document.
 * Uses NexusPro branding header and proper clinical formatting.
 */
export const exportNotesToPDF = ({
    title = 'Clinical Session Notes',
    clientTag,
    generatorType = 'RBT Session Notes',
    notes,
}: ExportOptions): void => {
    const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;

    // ─── Header ──────────────────────────────────────────────────────────
    doc.setFillColor(37, 99, 235); // NexusPro primary blue
    doc.rect(0, 0, pageWidth, 22, 'F');

    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('NexusPro', margin, 10);

    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    doc.text(generatorType, margin, 17);

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    doc.text(dateStr, pageWidth - margin, 17, { align: 'right' });

    // ─── Title ───────────────────────────────────────────────────────────
    doc.setTextColor(15, 23, 42);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(title, margin, 34);

    if (clientTag) {
        doc.setFontSize(10);
        doc.setTextColor(100, 116, 139);
        doc.setFont('helvetica', 'italic');
        doc.text(`Case: ${clientTag}`, margin, 41);
    }

    // ─── Divider ─────────────────────────────────────────────────────────
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.3);
    doc.line(margin, 45, pageWidth - margin, 45);

    // ─── Body Text ───────────────────────────────────────────────────────
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);

    const lines = doc.splitTextToSize(notes, contentWidth);
    let y = 52;
    const lineHeight = 5.5;
    const footerHeight = 15;

    for (const line of lines) {
        if (y + lineHeight > pageHeight - footerHeight) {
            // ─── Footer on each page ─────────────────────────────────────
            addFooter(doc, pageWidth, pageHeight, margin);
            doc.addPage();
            // Header on new page
            doc.setFillColor(37, 99, 235);
            doc.rect(0, 0, pageWidth, 22, 'F');
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(9);
            doc.setFont('helvetica', 'normal');
            doc.text('NexusPro — Continued', margin, 14);
            doc.setTextColor(30, 41, 59);
            doc.setFont('helvetica', 'normal');
            doc.setFontSize(10);
            y = 30;
        }
        doc.text(line, margin, y);
        y += lineHeight;
    }

    addFooter(doc, pageWidth, pageHeight, margin);

    // ─── Save ─────────────────────────────────────────────────────────────
    const safeName = (clientTag || 'notes').replace(/[^a-z0-9]/gi, '_').toLowerCase();
    const timestamp = now.toISOString().split('T')[0];
    doc.save(`nexuspro_${safeName}_${timestamp}.pdf`);
};

const addFooter = (doc: jsPDF, pageWidth: number, pageHeight: number, margin: number) => {
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.2);
    doc.line(margin, pageHeight - 10, pageWidth - margin, pageHeight - 10);
    doc.setFontSize(7.5);
    doc.setTextColor(148, 163, 184);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by NexusPro — Confidential Clinical Documentation', margin, pageHeight - 6);
    const pageCount = (doc.internal as any).getNumberOfPages?.() ?? 1;
    doc.text(`Page ${pageCount}`, pageWidth - margin, pageHeight - 6, { align: 'right' });
};
